create table feature_vec2(
	company_id varchar(10),
	CMark Varchar(10),
	oversea Varchar(6),
 	indust1	text,
	indust2	text,
	area Varchar(20),
	DayAverage float(10,5),
	Variation float(10,5),
	toIndust0 float(10,5),
	toIndust1 float(10,5),
	toIndust2 float(10,5),
	toIndust3 float(10,5),
	toIndust4 float(10,5),
	toIndust5 float(10,5),
	toIndust6 float(10,5),
	toIndust7 float(10,5),
	toIndust8 float(10,5),
	toIndust9 float(10,5),
	toIndust10 float(10,5),
	toIndust11 float(10,5),
	fromIndust0 float(10,5),
	fromIndust1 float(10,5),
	fromIndust2 float(10,5),
	fromIndust3 float(10,5),
	fromIndust4 float(10,5),
	fromIndust5 float(10,5),
	fromIndust6 float(10,5),
	fromIndust7 float(10,5),
	fromIndust8 float(10,5),
	fromIndust9 float(10,5),
	fromIndust10 float(10,5),
	fromIndust11 float(10,5),
	SendOverRec float(15,5),
	toIndust0_set longtext,
	toIndust1_set longtext,
	toIndust2_set longtext,
	toIndust3_set longtext,
	toIndust4_set longtext,
	toIndust5_set longtext,
	toIndust6_set longtext,
	toIndust7_set longtext,
	toIndust8_set longtext,
	toIndust9_set longtext,
	toIndust10_set longtext,
	toIndust11_set longtext,
	fromIndust0_set longtext,
	fromIndust1_set longtext,
	fromIndust2_set longtext,
	fromIndust3_set longtext,
	fromIndust4_set longtext,
	fromIndust5_set longtext,
	fromIndust6_set longtext,
	fromIndust7_set longtext,
	fromIndust8_set longtext,
	fromIndust9_set longtext,
	fromIndust10_set longtext,
	fromIndust11_set longtext

)CHARACTER SET utf8 COLLATE utf8_general_ci;

Load data infile '/Users/ruizhang/Documents/work/GT/research/SFexpress/data/FeatureExt/module/trainedDataFull/FeatureVector.txt' into table feature_vec2
 fields terminated by '\t' enclosed by '"' ignore 1 lines;
